name: Eric Garcia
favicon: null
layout_spectrum: 0.8116844927426428
typography_spectrum: 0.9333311012014747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#e7a324'
    - '#2960be'
    - '#695d2f'
    - '#cf2f4a'
  brandStrength: 0.4375
  lightness: 0.6117423078976572
  saturation: 0.75
  rhythmicContrast: 0.7361439573578537
purpose: []
