name: Eric Garcia
favicon: null
layout_spectrum: 0.8116844927426428
typography_spectrum: 0.9333311012014747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7660782332532108
  lightness: 0.6117423078976572
  saturation: 0.5406781022902578
  rhythmicContrast: 0.7361439573578537
purpose: []
